name: docker-pipeline-vasanth
on: push
jobs:
 docker-job:
   runs-on: ubuntu-latest
   steps:
     - name: print-22itl07
       run: echo "Hello World - 22ITL07"

     - name: checkout
       uses: actions/checkout@v4

     - name: Docker Build
       run: docker build -t vasanth414/ml-model-22itl07 .

     - name: Docker Images
        run: docker images

     - name: login to Docker Hub
       uses:  docker/login-actio@v3
       with: 
         username: ${{ vars.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Docker Push
         run: docker build -t vasanth414/ml-model-22itl07 .
